version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      - db
    environment:
      # For local development with local PostgreSQL
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@winston-public-1747647416.cpihf2p85fkq.us-east-1.rds.amazonaws.com:5432/winstongallery
      - SECRET_KEY=winston-gallery-secure-key-2025
      # For AWS resources
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_SECRET_ARN=${DB_SECRET_ARN}
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=winstongallery
    ports:
      - "5433:5432"  # Changed to 5433 to avoid conflicts with local PostgreSQL
    restart: always

volumes:
  postgres_data: